apiVersion: v1
kind: Service
metadata:
  labels:
    com.ubix.network: {{ .Values.netapi.name }}
  name: {{ .Values.netapi.name }}
spec:
  type: {{ .Values.netapi.service.type }}
  {{- if .Values.netapi.service.ports }}
  ports: {{- toYaml .Values.netapi.service.ports | nindent 4 }}
  {{- end }}
  selector:
    com.ubix.network: {{ .Values.netapi.name }}

