apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    com.ubix.network: {{ .Values.webapi.name }}
  name: {{ .Values.webapi.name }}
spec:
  replicas: {{ .Values.webapi.replicaCount }}
  selector:
    matchLabels:
      com.ubix.network: {{ .Values.webapi.name }}
  strategy:
    type: {{ .Values.webapi.updateStrategyType }}
  template:
    metadata:
      annotations:
      labels:
        com.ubix.network: {{ .Values.webapi.name }}
    spec:
    {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      containers:
        - image: "{{ .Values.global.registry }}/{{ .Values.webapi.image }}:{{ .Values.webapi.tag }}"
          name: {{ .Values.webapi.name }}
          {{- if .Values.webapi.ports }}
          ports: {{- toYaml .Values.webapi.ports | nindent 12 }}
          {{- end }}
          {{- if .Values.webapi.resources }}
          resources: {{- toYaml .Values.webapi.resources | nindent 12 }}
          {{- end }}
          {{- if .Values.webapi.volumeMounts }}
          volumeMounts: {{- toYaml .Values.webapi.volumeMounts | nindent 12 }}
          {{- end }}
          imagePullPolicy: {{ .Values.global.pullPolicy | quote }}
      {{- if .Values.webapi.volumes }}
      volumes: {{- toYaml .Values.webapi.volumes | nindent 8 }}
      {{- end }}
      {{- if .Values.cloudflare }}
      hostAliases: {{- toYaml .Values.webapi.hostAliases | nindent 6 }}
      {{- end }}

