apiVersion: v1
items:
  - apiVersion: networking.k8s.io/v1
    kind: Ingress
    metadata:
      annotations:
        nginx.ingress.kubernetes.io/rewrite-target: /$2
      name: coingame-api
    spec:
      {{- if .Values.google }}
      ingressClassName: nginx
      {{- end }}
      rules:
        - host: {{.Values.ingress.hostname }}
          http:
            paths:
              - backend:
                  service:
                    name: {{ .Values.webapi.name }}
                    port:
                      number: 3000
                path: /api(/|$)(.*)
                pathType: ImplementationSpecific
      tls:
        - hosts:
            - {{.Values.ingress.hostname }}
          secretName: coingame-ingress-tls-cert
    status:
      loadBalancer: {}
  - apiVersion: networking.k8s.io/v1
    kind: Ingress
    metadata:
      annotations:
        cert-manager.io/issuer: letsencrypt-api-coingame
      name: coingame-api-direct
    spec:
      {{- if .Values.google }}
      ingressClassName: nginx
      {{- end }}
      rules:
        - host: api.{{.Values.ingress.hostname }}
          http:
            paths:
              - backend:
                  service:
                    name: {{ .Values.webapi.name }}
                    port:
                      number: 3000
                path: /
                pathType: ImplementationSpecific
      tls:
        - hosts:
            - api.{{.Values.ingress.hostname }}
          secretName: coingame-api-ingress-tls-cert
kind: List
metadata: {}
