//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorMessage {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public ErrorMessage() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("App.Resources.ErrorMessage", typeof(ErrorMessage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string Between {
            get {
                return ResourceManager.GetString("Between", resourceCulture);
            }
        }
        
        public static string EntityNotFound {
            get {
                return ResourceManager.GetString("EntityNotFound", resourceCulture);
            }
        }
        
        public static string EntityNotFoundBy {
            get {
                return ResourceManager.GetString("EntityNotFoundBy", resourceCulture);
            }
        }
        
        public static string EntityRequiredWithOtherEntity {
            get {
                return ResourceManager.GetString("EntityRequiredWithOtherEntity", resourceCulture);
            }
        }
        
        public static string EnumError {
            get {
                return ResourceManager.GetString("EnumError", resourceCulture);
            }
        }
        
        public static string GreaterOrEqualTo {
            get {
                return ResourceManager.GetString("GreaterOrEqualTo", resourceCulture);
            }
        }
        
        public static string GreaterThan {
            get {
                return ResourceManager.GetString("GreaterThan", resourceCulture);
            }
        }
        
        public static string InvalidFormat {
            get {
                return ResourceManager.GetString("InvalidFormat", resourceCulture);
            }
        }
        
        public static string IsRequired {
            get {
                return ResourceManager.GetString("IsRequired", resourceCulture);
            }
        }
        
        public static string LessThan {
            get {
                return ResourceManager.GetString("LessThan", resourceCulture);
            }
        }
        
        public static string MaxLength {
            get {
                return ResourceManager.GetString("MaxLength", resourceCulture);
            }
        }
        
        public static string WrongSort {
            get {
                return ResourceManager.GetString("WrongSort", resourceCulture);
            }
        }
        
        public static string WrongValue {
            get {
                return ResourceManager.GetString("WrongValue", resourceCulture);
            }
        }
        
        public static string OneOfEntitiesShouldBe {
            get {
                return ResourceManager.GetString("OneOfEntitiesShouldBe", resourceCulture);
            }
        }
        
        public static string EqualTo {
            get {
                return ResourceManager.GetString("EqualTo", resourceCulture);
            }
        }
        
        public static string EntitiesNotFound {
            get {
                return ResourceManager.GetString("EntitiesNotFound", resourceCulture);
            }
        }
        
        public static string LessOrEqualTo {
            get {
                return ResourceManager.GetString("LessOrEqualTo", resourceCulture);
            }
        }
    }
}
