//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SecurityMessage {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public SecurityMessage() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("App.Resources.SecurityMessage", typeof(SecurityMessage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string AccountAlreadyExists {
            get {
                return ResourceManager.GetString("AccountAlreadyExists", resourceCulture);
            }
        }
        
        public static string AccountIsLocked {
            get {
                return ResourceManager.GetString("AccountIsLocked", resourceCulture);
            }
        }
        
        public static string AccountIsNotVerified {
            get {
                return ResourceManager.GetString("AccountIsNotVerified", resourceCulture);
            }
        }
        
        public static string LoginFailed {
            get {
                return ResourceManager.GetString("LoginFailed", resourceCulture);
            }
        }
        
        public static string MFACodeNotExists {
            get {
                return ResourceManager.GetString("MFACodeNotExists", resourceCulture);
            }
        }
        
        public static string PasswordFailed {
            get {
                return ResourceManager.GetString("PasswordFailed", resourceCulture);
            }
        }
        
        public static string PasswordPolicy {
            get {
                return ResourceManager.GetString("PasswordPolicy", resourceCulture);
            }
        }
        
        public static string SecurityCodeNotExists {
            get {
                return ResourceManager.GetString("SecurityCodeNotExists", resourceCulture);
            }
        }
        
        public static string WrongEmail {
            get {
                return ResourceManager.GetString("WrongEmail", resourceCulture);
            }
        }
        
        public static string WrongMFA {
            get {
                return ResourceManager.GetString("WrongMFA", resourceCulture);
            }
        }
    }
}
