apiVersion: v1
kind: Secret
type: Opaque
metadata:
{{ with .Values.postgres }}
  name: "{{ .username}}.{{.team}}-{{.cluster}}.credentials.postgresql.acid.zalan.do"
stringData:
  username: {{ .username }}
  password: {{ .password }}
{{ end }}
