<script setup lang="ts"></script>

<template>
  <div class="join-game-page">
    <div class="join-game-page__block-bg">
      <img class="join-game-page__bg-4" src="./images/sloy-4.png" alt="" srcset="" />
      <img class="join-game-page__bg-3" src="./images/sloy-3.png" alt="" srcset="" />
      <img class="join-game-page__bg-2" src="./images/sloy-2.png" alt="" srcset="" />
      <img class="join-game-page__bg-1" src="./images/sloy-1.png" alt="" srcset="" />
      <img class="join-game-page__bg-main" src="./images/main-bg.png" />
    </div>

    <div class="container">
      <div class="join-game-page__wrapper">
        <div class="join-game-page__title">112x_Coin_Game_pool_holder</div>

        <div class="join-game-page__info-block-1">
          <div class="join-game-page__subtitle">
            112HxA_Joining a pool & token staking
          </div>

          <div class="join-game-page__context">
            To join the coin tossing game pool and earn passive income, you’ll
            need to do two things:
          </div>

          <div class="join-game-page__list">
            <div class="join-game-page__item">
              <div class="join-game-page__number">1</div>
              <div class="">
                Buy some RPFC. RPFC is a T10 token issued on UBIX Network. You can
                buy it on Ubix.Exchange. <br />
                <a href="https://exchange.ubix.network/#/trade/RPFC-UBX">Ubix.Exchange token link</a> <br />All the
                proceeds from the
                sale of
                RPFC
                (apart
                from the fees charged by Ubix.Exchange) will be deposited in the
                corresponding risk liquidity pool agaisnt which the players will
                bid. <br />

                <span class="join-game-page__item--wallet">
                  Game pool wallet: <br />
                  Ux6af4ccb129e445c6b5ceccbdf2adfe9dd8a154bf
                </span>
              </div>
            </div>

            <div class="join-game-page__item">
              <div class="join-game-page__number">2</div>
              <div class="">
                To earn a passive income on your RPFC tokens, stake them on
                Ubistake (link). Part of the revenue generated by the game will
                be distributed among the stakes on a weekly basis.
              </div>
            </div>
          </div>
        </div>

        <div class="join-game-page__info-block-2">
          <div class="join-game-page__subtitle">
            112HxB_How protocol profit is generated
          </div>

          <div class="join-game-page__block-img">
            <img class="join-game-page__block-img--desktop" src="./images/bg.png" alt="" srcset="" />
            <img class="join-game-page__block-img--mobile" src="./images/bg-mobile.png" alt="" srcset="" />
          </div>

          <div class="join-game-page__context">
            Protocol revenue is distributed as follows: if a player loses, 20%
            of their bid is deposited in the risk pool to boost token backing.
            The remaining 80% is distributed among the pool’s stakers via
            ubistake.io.
          </div>
        </div>

        <div class="join-game-page__info-block-3">
          <div class="join-game-page__subtitle">112HxC_Platform fee</div>
          <div class="join-game-page__context">
            The 2% fee charged by the platform will be used to implement more
            complex risk frameworks and pools, such as insurance, forecasting,
            and trading. The current risk pool (the coin-tossing game) is merely
            a demonstration of how our protocol can help manage risks. Stay
            tuned for new feature releases!
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<style scoped lang="scss">
  @import "styles.module";
</style>
